### ISSUE TITLE
SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by schaefferp** [hisener/opsgenie-notifier#1]
Hi there !
I'm using `OG_HOST=https://api.eu.opsgenie.com`

```
$ npm install
npm WARN opsgenie-notifier@1.0.0 No repository field.

added 245 packages from 229 contributors and audited 559 packages in 4.487s
found 0 vulnerabilities

$ npm start

> opsgenie-notifier@1.0.0 start /Users/me/opsgenie-notifier
> node index.js

undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /Users/me/opsgenie-notifier/index.js:55:20
    at handleResponse (/Users/me/opsgenie-notifier/node_modules/opsgenie-sdk/lib/restApi.js:134:5)
    at Request.<anonymous> (/Users/me/opsgenie-notifier/node_modules/opsgenie-sdk/lib/restApi.js:110:9)
    at Request._callback (/Users/me/opsgenie-notifier/node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/Users/me/opsgenie-notifier/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/Users/me/opsgenie-notifier/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/Users/me/opsgenie-notifier/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/Users/me/opsgenie-notifier/node_modules/request/request.js:1161:10)
```

**Comment by hisener** [comment]
Hey, unfortunately, the project is not actively maintained. Feel free to fork.

**Comment by wdhif** [comment]
Hi, here is a quick and dirty fix for this.

https://github.com/wdhif/opsgenie-notifier

**Comment by hisener** [comment]
@wdhif Thanks for the fix!

**Comment by wdhif** [comment]
@hisener I can create a PR if you want ?

**Comment by hisener** [comment]
I'd be great.
